### ISSUE TITLE
Should text "NOT_EQAUL" be stayed in codebase? 

### ISSUE THREAD

**Issue by bachowsky** [besimgurbuz/ng-mat-table-filter#2]
I found that the operant NOT_EQUAL is tagged as NOT_EQAUL in filter-selection.ts and used in service as NOT_EQAUL. Should we correct this operant as NOT_EQUAL ? Or is there any reason behind the NOT_EQAUL tag?

**Comment by besimgurbuz** [comment]
It's a typo actually. I'll fix it. Thanks for letting me know.

**Comment by besimgurbuz** [comment]
Fixed with commit [2d089](https://github.com/besimgurbuz/ng-mat-table-filter/commit/2d0896bede05e481c571fa34814502620e1def3a)
